# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(999, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 70, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setToolTip("<html><head/><body><p align=\"center\"><br/></p></body></html>")
        self.label.setStyleSheet("border-image: url(:/pic/pngtree-vietnam-flag-border-background-picture-image_1177640.jpg);")
        self.label.setText("ỨNG DỤNG BÁN VÉ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(55)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 190, 771, 211))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-image: url(:/pic/mau-khung-hinh-nen-co-dien_022126362.jpg);")
        self.groupBox.setTitle("THÔNG TIN KHÁCH HÀNG")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 61, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setToolTip("<html><head/><body><p align=\"center\"><br/></p></body></html>")
        self.label_2.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.label_2.setText("HỌ TÊN:")
        self.label_2.setIndent(5)
        self.ho_ten = QtWidgets.QLineEdit(self.groupBox)
        self.ho_ten.setGeometry(QtCore.QRect(150, 30, 311, 22))
        self.ho_ten.setAutoFillBackground(False)
        self.ho_ten.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 81, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setToolTip("<html><head/><body><p align=\"center\"><br/></p></body></html>")
        self.label_3.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.label_3.setText("GIỚI TÍNH :")
        self.label_3.setIndent(5)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(190, 90, 73, 22))
        self.comboBox.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.comboBox.addItem("NAM")
        self.comboBox.addItem("NỮ")
        self.comboBox.addItem("KHÁC")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 61, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setToolTip("<html><head/><body><p align=\"center\"><br/></p></body></html>")
        self.label_4.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.label_4.setText("SĐT :")
        self.label_4.setIndent(5)
        self.ho_ten_2 = QtWidgets.QLineEdit(self.groupBox)
        self.ho_ten_2.setGeometry(QtCore.QRect(150, 150, 311, 22))
        self.ho_ten_2.setAutoFillBackground(False)
        self.ho_ten_2.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 430, 771, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border-image: url(:/pic/mau-khung-hinh-nen-co-dien_022126362.jpg);")
        self.groupBox_2.setTitle("DỊCH VỤ")
        self.ca_fe = QtWidgets.QCheckBox(self.groupBox_2)
        self.ca_fe.setGeometry(QtCore.QRect(90, 40, 81, 20))
        self.ca_fe.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.ca_fe.setText("CAFE")
        self.bim_bim = QtWidgets.QCheckBox(self.groupBox_2)
        self.bim_bim.setGeometry(QtCore.QRect(340, 40, 81, 20))
        self.bim_bim.setStyleSheet("border-image: url(:/pic/bang-trang-khung-nhom-nep-nho.webp);")
        self.bim_bim.setText("BIMBIM")
        self.nguoi_lon = QtWidgets.QSpinBox(self.groupBox_2)
        self.nguoi_lon.setGeometry(QtCore.QRect(170, 90, 42, 22))
